### ISSUE TITLE
[ Feat ] 챌린지 메인 구현

### ISSUE THREAD

**Issue by dogmania** [FOREGG-DEV/FOREGG_ANDROID_COMPOSE#53]
## TODO
- [ ] 챌린지 가입 화면 구현
- [ ] 챌린지 가입 API 연결
- [ ] 챌린지 메인 화면 구현
- [ ] 챌린지 메인 화면 API 연결
