### ISSUE TITLE
[ Fix ] 데일리허그 버그 수정 및 데일리허그 로티 적용

### ISSUE THREAD

**Issue by dogmania** [FOREGG-DEV/FOREGG_ANDROID_COMPOSE#55]
## TODO

- [x] 과거 데일리허그 삭제 시 날짜는 그대로 유지, 아이템은 최신 아이템이 렌더링되는 버그 수정
- [x] 데일리허그 작성 완료 로티 적용
- [x] 데일리허그 아이콘 적용
