### ISSUE TITLE
[ Feat ] 전체 챌린지 구현

### ISSUE THREAD

**Issue by dogmania** [FOREGG-DEV/FOREGG_ANDROID_COMPOSE#62]
## TODO

- [x] 전체 챌린지 조회 화면 구현
- [x] 전체 챌린지 조회 API 연결
- [x] 챌린지 상세 조회 화면 구현
- [x] 회원 탈퇴 시 저장된 챌린지 닉네임 삭제 구현
